/**
 * PlatformEvent — unified enterprise event structure.
 *
 * Append-only. Replay-safe. Serialization-safe. No circular payloads.
 * Maps 1:1 to the platform_events table.
 */

export interface GovernanceContext {
  policy_ids?:       string[]
  risk_score?:       number
  compliance_flags?: string[]
}

export interface EventMetadata {
  source?:     string
  ip?:         string
  device_id?:  string
  session_id?: string
}

export type EventSeverity = 'info' | 'warning' | 'high' | 'critical'

export interface PlatformEvent {
  /** Unique event identifier — generated by publisher if omitted */
  event_id?: string

  /** Matches EventType enum values */
  event_type: string

  /** Originating module: payroll | leave | attendance | compensation | employee | system */
  module: string

  /** DB entity type being acted upon */
  entity_type: string
  /** UUID of the affected entity */
  entity_id: string

  /** Tenant / organisation UUID */
  org_id: string
  /** Optional site/branch UUID */
  branch_id?: string

  /** User or system actor performing the action */
  actor_id?:   string
  actor_type?: 'user' | 'system' | 'scheduler' | 'webhook'

  /** ISO 8601 — set by publisher if omitted */
  timestamp?: string

  severity?: EventSeverity

  /** Domain-specific payload — keep flat, no circular refs */
  payload: Record<string, unknown>

  /** Links to a request correlation chain */
  correlation_id?: string
  /** Parent event UUID for cause-effect chains */
  parent_event_id?: string

  governance_context?: GovernanceContext
  metadata?:           EventMetadata
}

/** The resolved event (all optional fields populated by publisher) */
export interface ResolvedPlatformEvent extends PlatformEvent {
  event_id:  string
  timestamp: string
}
