/**
 * PolicyAssistant — inline RAG Q&A widget for the ESS policies page.
 * Employees can ask natural-language questions about company policies.
 * Answers are generated by Claude and cite the source policies.
 */
import { useRef, useEffect, useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { Bot, Send, BookOpen, ChevronDown, Sparkles } from 'lucide-react'
import { toast } from 'sonner'
import { api } from '@/lib/api/client'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface CitedPolicy { id: string; title: string; category: string }
interface QAEntry {
  question:        string
  answer:          string
  cited_policies:  CitedPolicy[]
}

interface AskResponse {
  answer:          string
  cited_policies:  CitedPolicy[]
}

const EXAMPLE_PROMPTS = [
  'How many casual leaves do I get per year?',
  'What is the work-from-home policy?',
  'How do I raise a harassment complaint?',
]

export function PolicyAssistant({ onOpenPolicy }: { onOpenPolicy: (id: string) => void }) {
  const [open, setOpen]   = useState(false)
  const [input, setInput] = useState('')
  const [history, setHistory] = useState<QAEntry[]>([])
  const bottomRef = useRef<HTMLDivElement>(null)
  const inputRef  = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (open) {
      bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
      inputRef.current?.focus()
    }
  }, [history, open])

  const ask = useMutation({
    mutationFn: (question: string) =>
      api.post<{ data: AskResponse }>('/policies/ask', { question }).then(r => r.data),
    onSuccess: (data, question) => {
      setHistory(h => [...h, {
        question,
        answer:         data.answer,
        cited_policies: data.cited_policies,
      }])
      setInput('')
    },
    onError: (e: Error) => toast.error('Policy Assistant error', { description: e.message }),
  })

  const submit = () => {
    const q = input.trim()
    if (!q || ask.isPending) return
    ask.mutate(q)
  }

  const applyPrompt = (p: string) => {
    setInput(p)
    ask.mutate(p)
  }

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      {/* ── Header (always visible, toggles body) ── */}
      <button
        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-muted/30 transition-colors"
        onClick={() => setOpen(o => !o)}
      >
        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary shrink-0">
          <Sparkles className="h-4 w-4" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-foreground">Policy Assistant</p>
          <p className="text-[11px] text-muted-foreground">Ask AI questions about company policies</p>
        </div>
        <ChevronDown
          className={cn('h-4 w-4 text-muted-foreground transition-transform duration-200', open && 'rotate-180')}
        />
      </button>

      {/* ── Body ── */}
      {open && (
        <div className="border-t border-border flex flex-col">
          {/* Conversation history */}
          {history.length > 0 ? (
            <div className="max-h-96 overflow-y-auto px-4 pt-4 pb-2 space-y-5">
              {history.map((entry, i) => (
                <div key={i} className="space-y-2.5">
                  {/* User bubble */}
                  <div className="flex justify-end">
                    <div className="bg-primary text-primary-foreground rounded-2xl rounded-tr-sm px-3.5 py-2 text-sm max-w-[80%] leading-snug">
                      {entry.question}
                    </div>
                  </div>
                  {/* Assistant bubble */}
                  <div className="flex gap-2.5 items-start">
                    <div className="flex h-6 w-6 items-center justify-center rounded-full bg-muted text-muted-foreground shrink-0 mt-0.5">
                      <Bot className="h-3.5 w-3.5" />
                    </div>
                    <div className="flex-1 min-w-0 space-y-1.5">
                      <div className="bg-muted/50 rounded-2xl rounded-tl-sm px-3.5 py-2.5 text-sm text-foreground leading-relaxed whitespace-pre-wrap">
                        {entry.answer}
                      </div>
                      {entry.cited_policies.length > 0 && (
                        <div className="pl-1 flex flex-wrap gap-1.5">
                          <span className="text-[10px] text-muted-foreground">Sources:</span>
                          {entry.cited_policies.map(p => (
                            <button
                              key={p.id}
                              onClick={() => onOpenPolicy(p.id)}
                              className="flex items-center gap-1 text-[10px] text-primary hover:underline"
                            >
                              <BookOpen className="h-3 w-3" />
                              {p.title}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}

              {/* Pending indicator */}
              {ask.isPending && (
                <div className="flex gap-2.5 items-center">
                  <div className="flex h-6 w-6 items-center justify-center rounded-full bg-muted text-muted-foreground shrink-0">
                    <Bot className="h-3.5 w-3.5" />
                  </div>
                  <div className="bg-muted/50 rounded-2xl rounded-tl-sm px-3.5 py-2.5">
                    <span className="flex gap-1">
                      <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground animate-bounce [animation-delay:0ms]" />
                      <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground animate-bounce [animation-delay:150ms]" />
                      <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground animate-bounce [animation-delay:300ms]" />
                    </span>
                  </div>
                </div>
              )}
              <div ref={bottomRef} />
            </div>
          ) : (
            /* Empty state with example prompts */
            <div className="px-4 pt-5 pb-2">
              {!ask.isPending && (
                <>
                  <p className="text-xs text-muted-foreground text-center mb-3">
                    Ask anything about company policies — leave, benefits, conduct, IT, and more.
                  </p>
                  <div className="flex flex-wrap gap-1.5 justify-center">
                    {EXAMPLE_PROMPTS.map(p => (
                      <button
                        key={p}
                        onClick={() => applyPrompt(p)}
                        className="text-[11px] px-2.5 py-1 rounded-full border border-border text-muted-foreground hover:bg-muted/50 hover:text-foreground transition-colors"
                      >
                        {p}
                      </button>
                    ))}
                  </div>
                </>
              )}
              {ask.isPending && (
                <div className="flex gap-2.5 items-center justify-center py-4">
                  <Bot className="h-4 w-4 text-muted-foreground animate-pulse" />
                  <span className="text-xs text-muted-foreground">Searching policies…</span>
                </div>
              )}
            </div>
          )}

          {/* ── Input bar ── */}
          <div className="px-4 py-3 flex gap-2 border-t border-border/50 bg-muted/20">
            <input
              ref={inputRef}
              type="text"
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={e => {
                if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit() }
              }}
              placeholder="Ask about any policy…"
              className="flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus:border-primary placeholder:text-muted-foreground/70 disabled:opacity-50"
              disabled={ask.isPending}
              maxLength={400}
            />
            <Button
              size="icon"
              onClick={submit}
              disabled={!input.trim() || ask.isPending}
              className="h-9 w-9 shrink-0"
            >
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
