/**
 * GET /attendance/pipeline-stats
 *
 * Returns operational metrics for BOTH attendance pipelines in a single call:
 *
 *  Pipeline A — Biometric / Device (attendance_raw_logs → batch processor)
 *    raw_log_count_30d     : punches ingested from devices in the last 30 days
 *    processing_runs_30d   : batch-processor run count in the last 30 days
 *    last_batch_run_date   : most recent run date (YYYY-MM-DD)
 *    last_batch_ran_at     : ISO timestamp of the most recent completed run
 *    batch_employees_last  : employees processed in the most recent batch run
 *
 *  Pipeline B — CSV Upload Recompute (attendance_punch_logs → recomputeRange → attendance_daily)
 *    punch_log_count_30d   : CSV-sourced punch rows in last 30 days
 *    csv_employees_30d     : distinct employees present in CSV uploads (last 30d)
 *    daily_rows_from_csv   : attendance_daily rows with computed_source = 'engine' (all time)
 *    csv_date_range        : { from, to } — earliest / latest date in punch_logs (last 30d), or null
 *    upload_count_30d      : completed upload sessions in last 30 days
 *    last_upload_at        : ISO timestamp of most recent completed upload
 *
 *  Source detection
 *    active_source         : 'csv' | 'biometric' | 'hybrid' | 'none'
 *      csv       — only CSV punch_logs have data in last 30d
 *      biometric — only raw_logs have data in last 30d
 *      hybrid    — both have data in last 30d
 *      none      — neither has data
 *
 * Auth: hr_admin / super_admin only (same as upload-health).
 */

import type { FastifyInstance } from 'fastify'
import { requireRole, HR_ADMIN_ROLES } from '../../lib/rbac.js'
import { fetchAllRows } from '../../lib/supabase-paginate.js'

export default async function attendancePipelineStatsRoute(fastify: FastifyInstance) {
  const adminAuth = { preHandler: [fastify.authenticate, requireRole(...HR_ADMIN_ROLES)] }

  fastify.get('/attendance/pipeline-stats', adminAuth, async (req: any, reply) => {
    const tenantId  = req.tenantId
    const since30d  = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()

    // ── Distinct employees — fetched separately to avoid PostgREST 1000-row cap ─
    const punchEmpRows = await fetchAllRows((from, to) =>
      fastify.supabase
        .from('attendance_punch_logs')
        .select('employee_id')
        .eq('tenant_id', tenantId)
        .eq('source', 'csv_upload')
        .gte('created_at', since30d)
        .range(from, to),
    ).catch(() => [] as { employee_id: string }[])

    // ── Run all queries in parallel ──────────────────────────────────────────
    const [
      // Pipeline B: CSV punch log count + date range
      punchLogResult,
      // Pipeline B: attendance_daily rows generated by engine (all time)
      dailyFromEngineResult,
      // Pipeline B: upload session count + last upload
      uploadSessionResult,
      // Pipeline A: raw_log count in last 30d
      rawLogResult,
      // Pipeline A: processing run count in last 30d
      runCountResult,
      // Pipeline A: last batch run summary
      lastRunResult,
    ] = await Promise.all([
      // attendance_punch_logs — count + min/max date for csv_upload source, last 30d
      fastify.supabase
        .from('attendance_punch_logs')
        .select('date:punched_at', { count: 'exact', head: false })
        .eq('tenant_id', tenantId)
        .eq('source', 'csv_upload')
        .gte('created_at', since30d)
        .order('punched_at', { ascending: true })
        .limit(1),

      // attendance_daily rows written by engine (source = 'engine') — all time
      fastify.supabase
        .from('attendance_daily')
        .select('id', { count: 'exact', head: true })
        .eq('tenant_id', tenantId)
        .eq('computed_source', 'engine'),

      // Latest completed upload session
      fastify.supabase
        .from('upload_sessions')
        .select('id, created_at', { count: 'exact', head: false })
        .eq('tenant_id', tenantId)
        .eq('upload_type', 'attendance_csv')
        .eq('status', 'completed')
        .gte('created_at', since30d)
        .order('created_at', { ascending: false })
        .limit(1),

      // attendance_raw_logs — count in last 30d (biometric pipeline signal)
      fastify.supabase
        .from('attendance_raw_logs')
        .select('id', { count: 'exact', head: true })
        .eq('tenant_id', tenantId)
        .gte('created_at', since30d),

      // attendance_processing_runs — count in last 30d
      fastify.supabase
        .from('attendance_processing_runs')
        .select('id', { count: 'exact', head: true })
        .eq('tenant_id', tenantId)
        .gte('started_at', since30d),

      // Most recent completed batch run
      fastify.supabase
        .from('attendance_processing_runs')
        .select('date, processed_count, completed_at, error_message')
        .eq('tenant_id', tenantId)
        .not('completed_at', 'is', null)
        .order('started_at', { ascending: false })
        .limit(1)
        .maybeSingle(),
    ])

    // ── Pipeline A: biometric ────────────────────────────────────────────────
    const rawLogCount30d      = rawLogResult.count ?? 0
    const processingRuns30d   = runCountResult.count ?? 0
    const lastBatchRun        = lastRunResult.data as {
      date: string; processed_count: number; completed_at: string; error_message: string | null
    } | null

    // ── Pipeline B: CSV ──────────────────────────────────────────────────────
    const punchLogCount30d    = punchLogResult.count ?? 0
    const punchLogRows        = (punchLogResult.data ?? []) as Array<{ date: string }>

    // Distinct employees
    const csvEmployees30d     = new Set(punchEmpRows.map((r) => r.employee_id)).size

    // Daily rows from engine
    const dailyFromEngine     = dailyFromEngineResult.count ?? 0

    // Upload sessions
    const uploadSessions      = (uploadSessionResult.data ?? []) as Array<{ id: string; created_at: string }>
    const uploadCount30d      = uploadSessionResult.count ?? 0
    const lastUploadAt        = uploadSessions[0]?.created_at ?? null

    // Date range from punch logs — fetch min & max in a second targeted query if we have rows
    let csvDateRange: { from: string; to: string } | null = null
    if (punchLogCount30d > 0) {
      // Get the latest date in a separate query
      const { data: latestRow } = await fastify.supabase
        .from('attendance_punch_logs')
        .select('date:punched_at')
        .eq('tenant_id', tenantId)
        .eq('source', 'csv_upload')
        .gte('created_at', since30d)
        .order('punched_at', { ascending: false })
        .limit(1)
        .maybeSingle()

      const earliest = punchLogRows[0]?.date
      const latest   = (latestRow as { date: string } | null)?.date
      if (earliest && latest) {
        csvDateRange = { from: earliest, to: latest }
      }
    }

    // ── Source detection ─────────────────────────────────────────────────────
    const hasCsv       = punchLogCount30d > 0
    const hasBiometric = rawLogCount30d   > 0
    let activeSource: 'csv' | 'biometric' | 'hybrid' | 'none' = 'none'
    if (hasCsv && hasBiometric) activeSource = 'hybrid'
    else if (hasCsv)            activeSource = 'csv'
    else if (hasBiometric)      activeSource = 'biometric'

    return reply.send({
      // Pipeline A — Biometric
      raw_log_count_30d:      rawLogCount30d,
      processing_runs_30d:    processingRuns30d,
      last_batch_run_date:    lastBatchRun?.date                ?? null,
      last_batch_ran_at:      lastBatchRun?.completed_at        ?? null,
      batch_employees_last:   lastBatchRun?.processed_count     ?? null,
      batch_last_error:       lastBatchRun?.error_message       ?? null,

      // Pipeline B — CSV
      punch_log_count_30d:    punchLogCount30d,
      csv_employees_30d:      csvEmployees30d,
      daily_rows_from_csv:    dailyFromEngine,
      csv_date_range:         csvDateRange,
      upload_count_30d:       uploadCount30d,
      last_upload_at:         lastUploadAt,

      // Source detection
      active_source:          activeSource,
    })
  })
}
