/**
 * compensation-engine.ts
 *
 * Deterministic, reusable engine for computing employee compensation.
 * Mirrors the AttendanceEngine pattern — pure functions, no DB calls.
 *
 * Calculation order (strictly sequential):
 *   1. Sort components by sequence
 *   2. Compute pct_of_ctc earnings
 *   3. Identify and compute BASIC (anchor)
 *   4. Compute pct_of_basic earnings
 *   5. Compute remaining fixed earnings
 *   6. Compute pct_of_gross earnings (using gross from steps 3-5)
 *   7. Compute gross total
 *   8. Apply NLC adjustment if enabled (Basic + NLC-tagged >= 50 % of Gross)
 *   9. Compute deductions and employer-contributions
 *  10. Inject PF deduction + employer-contribution if PF enabled
 *  11. Build result with totals
 *
 * Error conditions:
 *   - CTC ≤ 0                          → throws
 *   - No components supplied            → throws
 *   - pct_of_basic component present
 *     but no BASIC anchor found         → throws
 */

// ── Public types ───────────────────────────────────────────────────────────────

export interface ComponentInput {
  /** salary_component.id — opaque UUID passed through to output */
  salary_component_id: string
  name:                string
  code:                string
  component_type:      'earning' | 'deduction' | 'employer_contribution'
  calc_type:           'pct_of_ctc' | 'pct_of_basic' | 'pct_of_gross' | 'fixed'
  /** Percentage (e.g. 40 = 40 %) for pct_* types; monthly rupees for fixed */
  value:               number
  /** Determines computation order; lower = earlier */
  sequence:            number
  /** True for exactly one earning component — the Basic Salary anchor */
  is_basic:            boolean
  /** Component is included in the PF wage base (in addition to Basic) */
  affects_pf:          boolean
  /** Component counts toward NLC wage threshold alongside Basic (e.g. DA) */
  affects_nlc:         boolean
}

export interface EmployeeFlags {
  /** Employee is enrolled in PF */
  pf_enabled: boolean
  /** Cap PF base at policy.pf_cap_amount (₹15,000/month) */
  pf_capped:  boolean
}

export interface CompensationPolicy {
  /** Enforce New Labour Code: Basic + NLC-tagged >= 50 % of Gross */
  nlc_enabled:        boolean
  /** Tenant-level PF switch; also requires employee.pf_enabled */
  pf_enabled:         boolean
  /** Employee PF contribution rate (%) — typically 12 */
  pf_employee_rate:   number
  /** Employer PF contribution rate (%) — typically 12 */
  pf_employer_rate:   number
  /** Monthly wage ceiling for PF base (₹15,000 statutory default) */
  pf_cap_amount:      number
}

export interface ComputedComponent {
  salary_component_id:   string
  name:                  string
  code:                  string
  component_type:        'earning' | 'deduction' | 'employer_contribution'
  calc_type:             string
  value:                 number
  sequence:              number
  is_basic:              boolean
  affects_pf:            boolean
  affects_nlc:           boolean
  /** Rupees / month (stored in employee_compensation_components.computed_monthly) */
  monthly_amount:        number
  /** Rupees / year  (stored in employee_compensation_components.computed_annual) */
  annual_amount:         number
  /**
   * True when this component was generated by the engine (PF entries).
   * The route layer must resolve the salary_component_id before persisting.
   */
  is_engine_generated?: boolean
}

export interface CompensationTotals {
  gross_monthly:                   number
  gross_annual:                    number
  basic_monthly:                   number
  basic_annual:                    number
  deductions_monthly:              number
  deductions_annual:               number
  employer_contributions_monthly:  number
  employer_contributions_annual:   number
  /** gross - employee deductions */
  net_monthly:                     number
  net_annual:                      number
}

export interface CompensationResult {
  components:      ComputedComponent[]
  totals:          CompensationTotals
  nlc_applied:     boolean
  pf_applied:      boolean
  /** Basic + NLC-tagged as % of Gross, post-adjustment.  null if NLC disabled. */
  nlc_wage_pct:    number | null
}

// ── Built-in defaults ─────────────────────────────────────────────────────────

export const DEFAULT_COMPENSATION_POLICY: Readonly<CompensationPolicy> = Object.freeze({
  nlc_enabled:      true,
  pf_enabled:       false,    // off by default; tenant opts in
  pf_employee_rate: 12.0,
  pf_employer_rate: 12.0,
  pf_cap_amount:    15_000,   // ₹15,000 / month (EPF Act ceiling)
})

// ── PF sentinel IDs ───────────────────────────────────────────────────────────
// Route layer replaces these with real salary_component.id values before
// persisting to employee_compensation_components.

export const PF_EMPLOYEE_SENTINEL = '__pf_employee__'
export const PF_EMPLOYER_SENTINEL = '__pf_employer__'
export const PF_EMPLOYEE_CODE     = 'PF_EMPLOYEE'
export const PF_EMPLOYER_CODE     = 'PF_EMPLOYER'

// ── Internal helpers ──────────────────────────────────────────────────────────

/** Round to 2 decimal places (financial rounding) */
function r2(n: number): number {
  return Math.round(n * 100) / 100
}

/** Accumulate annual amounts for a subset of computed components */
function sumAnnual(comps: ComputedComponent[]): number {
  return r2(comps.reduce((acc, c) => acc + c.annual_amount, 0))
}

// ── Main export ───────────────────────────────────────────────────────────────

export interface ComputeCompensationParams {
  ctcAnnual:  number
  components: ComponentInput[]
  employee:   EmployeeFlags
  policy:     CompensationPolicy
}

/**
 * computeCompensation
 *
 * Pure function — no side effects, no DB calls.
 * Input `value` fields are NEVER mutated; NLC/PF adjustments are reflected
 * exclusively in the returned monthly_amount / annual_amount fields.
 *
 * Throws:
 *   - 'CTC_INVALID'   if ctcAnnual ≤ 0
 *   - 'NO_COMPONENTS' if the components array is empty
 *   - 'MISSING_BASIC' if any pct_of_basic earning exists without a BASIC anchor
 *   - 'CIRCULAR_DEP'  if a pct_of_gross component depends on itself  (not possible
 *                     via current calc_type set, but guard remains for safety)
 */
export function computeCompensation({
  ctcAnnual,
  components,
  employee,
  policy,
}: ComputeCompensationParams): CompensationResult {

  // ── Guard: validate inputs ─────────────────────────────────────────────────
  if (ctcAnnual <= 0)       throw Object.assign(new Error('CTC must be positive'),            { code: 'CTC_INVALID'   })
  if (!components.length)   throw Object.assign(new Error('At least one component required'), { code: 'NO_COMPONENTS' })

  // ── 1. Separate by component_type; sort each group by sequence ─────────────
  const earnings       = components.filter(c => c.component_type === 'earning')
                                    .sort((a, b) => a.sequence - b.sequence)
  const deductions     = components.filter(c => c.component_type === 'deduction')
                                    .sort((a, b) => a.sequence - b.sequence)
  const employerContrib = components.filter(c => c.component_type === 'employer_contribution')
                                    .sort((a, b) => a.sequence - b.sequence)

  // Guard: pct_of_basic requires a BASIC anchor
  const hasPctOfBasic = earnings.some(c => c.calc_type === 'pct_of_basic')
  const basicComp     = earnings.find(c => c.is_basic)
                        ?? earnings.find(c => c.calc_type === 'fixed' || c.calc_type === 'pct_of_ctc')

  if (hasPctOfBasic && !basicComp) {
    throw Object.assign(
      new Error(
        'BASIC salary component not found. ' +
        'Mark one earning component with is_basic=true, ' +
        'or ensure a fixed/pct_of_ctc earning precedes pct_of_basic components.',
      ),
      { code: 'MISSING_BASIC' },
    )
  }

  // ── amounts map: salary_component_id → annual rupees ─────────────────────
  const amounts = new Map<string, number>()

  // ── 2. Compute pct_of_ctc earnings ────────────────────────────────────────
  for (const c of earnings.filter(e => e.calc_type === 'pct_of_ctc')) {
    amounts.set(c.salary_component_id, r2((c.value / 100) * ctcAnnual))
  }

  // ── 3. Compute BASIC ──────────────────────────────────────────────────────
  let basicAnnual = 0
  if (basicComp) {
    if (basicComp.calc_type === 'fixed') {
      basicAnnual = r2(basicComp.value * 12)
    } else if (basicComp.calc_type === 'pct_of_ctc') {
      // already computed in step 2; re-read from map (or compute if missing)
      basicAnnual = amounts.get(basicComp.salary_component_id)
                   ?? r2((basicComp.value / 100) * ctcAnnual)
    }
    amounts.set(basicComp.salary_component_id, basicAnnual)
  }

  // ── 4. Compute pct_of_basic earnings ──────────────────────────────────────
  for (const c of earnings.filter(e => e.calc_type === 'pct_of_basic')) {
    amounts.set(c.salary_component_id, r2((c.value / 100) * basicAnnual))
  }

  // ── 5. Compute remaining fixed earnings (non-basic) ───────────────────────
  for (const c of earnings.filter(e => e.calc_type === 'fixed' && !e.is_basic)) {
    amounts.set(c.salary_component_id, r2(c.value * 12))
  }

  // ── 6. Compute pct_of_gross earnings ──────────────────────────────────────
  // Gross = sum of all earnings computed so far (pct_of_ctc + fixed + pct_of_basic)
  let grossAnnual = r2(earnings.reduce((acc, c) => acc + (amounts.get(c.salary_component_id) ?? 0), 0))

  for (const c of earnings.filter(e => e.calc_type === 'pct_of_gross')) {
    const a = r2((c.value / 100) * grossAnnual)
    amounts.set(c.salary_component_id, a)
    grossAnnual = r2(grossAnnual + a)   // accumulate incrementally
  }

  // ── 7. Finalize gross ─────────────────────────────────────────────────────
  grossAnnual = r2(earnings.reduce((acc, c) => acc + (amounts.get(c.salary_component_id) ?? 0), 0))

  // ── 8. NLC enforcement ────────────────────────────────────────────────────
  let nlcApplied  = false
  let nlcWagePct: number | null = null

  if (policy.nlc_enabled && basicComp && grossAnnual > 0) {
    // NLC wage = Basic + any component tagged affects_nlc (e.g. DA)
    const nlcWageAnnual = basicAnnual
      + r2(earnings
          .filter(c => !c.is_basic && c.affects_nlc)
          .reduce((acc, c) => acc + (amounts.get(c.salary_component_id) ?? 0), 0))

    nlcWagePct = r2((nlcWageAnnual / grossAnnual) * 100)

    if (nlcWagePct < 50) {
      const required = r2(grossAnnual * 0.5)
      const deficit  = r2(required - nlcWageAnnual)

      // Find the most flexible earning to reduce:
      //   not the basic anchor, not NLC-tagged, is an earning component
      const flexible = earnings.find(c =>
        !c.is_basic &&
        !c.affects_nlc &&
        c.component_type === 'earning' &&
        (amounts.get(c.salary_component_id) ?? 0) > 0
      )

      if (flexible && deficit > 0) {
        const flexCurrent = amounts.get(flexible.salary_component_id) ?? 0
        const reduction   = r2(Math.min(deficit, flexCurrent))

        if (reduction > 0) {
          // Reduce flexible component
          amounts.set(flexible.salary_component_id, r2(flexCurrent - reduction))

          // Increase Basic by the same amount to preserve total CTC
          basicAnnual = r2(basicAnnual + reduction)
          amounts.set(basicComp.salary_component_id, basicAnnual)

          // Recompute all pct_of_basic components with new basicAnnual
          for (const c of earnings.filter(e => e.calc_type === 'pct_of_basic')) {
            amounts.set(c.salary_component_id, r2((c.value / 100) * basicAnnual))
          }

          // Recompute gross (all earnings)
          grossAnnual = r2(earnings.reduce((acc, c) => acc + (amounts.get(c.salary_component_id) ?? 0), 0))

          // Update nlcWagePct post-adjustment
          const newNlcWage = basicAnnual
            + r2(earnings
                .filter(c => !c.is_basic && c.affects_nlc)
                .reduce((acc, c) => acc + (amounts.get(c.salary_component_id) ?? 0), 0))
          nlcWagePct = grossAnnual > 0 ? r2((newNlcWage / grossAnnual) * 100) : 0

          nlcApplied = true
        }
      }
    }
  }

  // ── 9. Compute deductions and employer-contributions ──────────────────────
  function computeOtherComponent(c: ComponentInput): void {
    let annual = 0
    switch (c.calc_type) {
      case 'fixed':        annual = r2(c.value * 12);                         break
      case 'pct_of_ctc':  annual = r2((c.value / 100) * ctcAnnual);          break
      case 'pct_of_basic': annual = r2((c.value / 100) * basicAnnual);        break
      case 'pct_of_gross': annual = r2((c.value / 100) * grossAnnual);        break
    }
    amounts.set(c.salary_component_id, annual)
  }

  for (const c of deductions)      computeOtherComponent(c)
  for (const c of employerContrib) computeOtherComponent(c)

  // ── 10. PF injection ──────────────────────────────────────────────────────
  let pfApplied = false
  const pfComponents: ComputedComponent[] = []

  const pfEnabled = policy.pf_enabled && employee.pf_enabled && basicComp

  if (pfEnabled) {
    const basicMonthly = r2(basicAnnual / 12)
    let   pfBase       = basicMonthly

    if (employee.pf_capped) {
      pfBase = r2(Math.min(pfBase, policy.pf_cap_amount))
    }

    const empPfMonthly = r2(pfBase * (policy.pf_employee_rate / 100))
    const erPfMonthly  = r2(pfBase * (policy.pf_employer_rate / 100))

    pfComponents.push({
      salary_component_id: PF_EMPLOYEE_SENTINEL,
      name:                'PF Employee Contribution',
      code:                PF_EMPLOYEE_CODE,
      component_type:      'deduction',
      calc_type:           'pct_of_basic',
      value:               policy.pf_employee_rate,
      sequence:            9000,
      is_basic:            false,
      affects_pf:          false,
      affects_nlc:         false,
      monthly_amount:      empPfMonthly,
      annual_amount:       r2(empPfMonthly * 12),
      is_engine_generated: true,
    })

    pfComponents.push({
      salary_component_id: PF_EMPLOYER_SENTINEL,
      name:                'PF Employer Contribution',
      code:                PF_EMPLOYER_CODE,
      component_type:      'employer_contribution',
      calc_type:           'pct_of_basic',
      value:               policy.pf_employer_rate,
      sequence:            9001,
      is_basic:            false,
      affects_pf:          false,
      affects_nlc:         false,
      monthly_amount:      erPfMonthly,
      annual_amount:       r2(erPfMonthly * 12),
      is_engine_generated: true,
    })

    pfApplied = true
  }

  // ── 11. Build ComputedComponent list ─────────────────────────────────────
  const inputComputed: ComputedComponent[] = [
    ...earnings,
    ...deductions,
    ...employerContrib,
  ].map(c => {
    const annual  = amounts.get(c.salary_component_id) ?? 0
    return {
      salary_component_id: c.salary_component_id,
      name:                c.name,
      code:                c.code,
      component_type:      c.component_type,
      calc_type:           c.calc_type,
      value:               c.value,
      sequence:            c.sequence,
      is_basic:            c.is_basic,
      affects_pf:          c.affects_pf,
      affects_nlc:         c.affects_nlc,
      monthly_amount:      r2(annual / 12),
      annual_amount:       annual,
    }
  })

  const allComponents = [...inputComputed, ...pfComponents]

  // ── 12. Totals ────────────────────────────────────────────────────────────
  const allEarnings       = allComponents.filter(c => c.component_type === 'earning')
  const allDeductions     = allComponents.filter(c => c.component_type === 'deduction')
  const allEmployerCon    = allComponents.filter(c => c.component_type === 'employer_contribution')

  const grossAnnualFinal  = sumAnnual(allEarnings)
  const deductAnnual      = sumAnnual(allDeductions)
  const employerConAnnual = sumAnnual(allEmployerCon)

  const totals: CompensationTotals = {
    gross_annual:                   grossAnnualFinal,
    gross_monthly:                  r2(grossAnnualFinal / 12),
    basic_annual:                   r2(basicAnnual),
    basic_monthly:                  r2(basicAnnual / 12),
    deductions_annual:              deductAnnual,
    deductions_monthly:             r2(deductAnnual / 12),
    employer_contributions_annual:  employerConAnnual,
    employer_contributions_monthly: r2(employerConAnnual / 12),
    net_annual:                     r2(grossAnnualFinal - deductAnnual),
    net_monthly:                    r2((grossAnnualFinal - deductAnnual) / 12),
  }

  // ── Validation ─────────────────────────────────────────────────────────────
  // Warn (don't throw) if gross does not match CTC — possible with pct_of_gross
  // residual mismatches. Callers can decide to surface this.
  const epsilon = 1  // ₹1 tolerance for floating-point noise
  if (Math.abs(grossAnnualFinal - ctcAnnual) > epsilon && process.env.NODE_ENV !== 'test') {
    // Log to stderr so it doesn't end up in structured output
    process.stderr.write(
      JSON.stringify({
        level:   'warn',
        service: 'compensation-engine',
        action:  'gross_ctc_mismatch',
        ctc:     ctcAnnual,
        gross:   grossAnnualFinal,
        diff:    r2(grossAnnualFinal - ctcAnnual),
      }) + '\n',
    )
  }

  return {
    components:   allComponents,
    totals,
    nlc_applied:  nlcApplied,
    pf_applied:   pfApplied,
    nlc_wage_pct: policy.nlc_enabled ? nlcWagePct : null,
  }
}
