/**
 * compensation-engine.ts
 *
 * Deterministic, reusable engine for computing employee compensation.
 * Mirrors the AttendanceEngine pattern — pure functions, no DB calls.
 *
 * Calculation order (strictly sequential):
 *   1. Sort components by sequence
 *   2. Compute pct_of_ctc earnings
 *   3. Identify and compute BASIC (anchor)
 *   4. Compute pct_of_basic earnings
 *   5. Compute remaining fixed earnings
 *   6. Compute pct_of_gross earnings (using gross from steps 3-5)
 *   7. Compute gross total
 *   8. Apply NLC adjustment if enabled (Basic + NLC-tagged >= 50 % of Gross)
 *   9. Compute deductions and employer-contributions
 *  10. Inject PF deduction + employer-contribution if PF enabled
 *  11. Build result with totals
 *
 * Error conditions:
 *   - CTC ≤ 0                          → throws
 *   - No components supplied            → throws
 *   - pct_of_basic component present
 *     but no BASIC anchor found         → throws
 */

// ── Public types ───────────────────────────────────────────────────────────────

export interface ComponentInput {
  /** salary_component.id — opaque UUID passed through to output */
  salary_component_id: string
  name:                string
  code:                string
  component_type:      'earning' | 'deduction' | 'employer_contribution'
  calc_type:           'pct_of_ctc' | 'pct_of_basic' | 'pct_of_gross' | 'fixed' | 'balance'
  /**
   * Percentage (e.g. 40 = 40 %) for pct_* types; monthly rupees for fixed.
   * IGNORED for 'balance' — that component is the residual (CTC − everything else).
   */
  value:               number
  /** Determines computation order; lower = earlier */
  sequence:            number
  /** True for exactly one earning component — the Basic Salary anchor */
  is_basic:            boolean
  /** Component is included in the PF wage base (in addition to Basic) */
  affects_pf:          boolean
  /** Component counts toward NLC wage threshold alongside Basic (e.g. DA) */
  affects_nlc:         boolean
}

export interface EmployeeFlags {
  /** Employee is enrolled in PF */
  pf_enabled: boolean
  /** Cap PF base at policy.pf_cap_amount (₹15,000/month) */
  pf_capped:  boolean
}

export interface CompensationPolicy {
  /** Enforce New Labour Code: Basic + NLC-tagged >= 50 % of Gross */
  nlc_enabled:        boolean
  /** Tenant-level PF switch; also requires employee.pf_enabled */
  pf_enabled:         boolean
  /** Employee PF contribution rate (%) — typically 12 */
  pf_employee_rate:   number
  /** Employer PF contribution rate (%) — typically 12 */
  pf_employer_rate:   number
  /** Monthly wage ceiling for PF base (₹15,000 statutory default) */
  pf_cap_amount:      number
}

export interface ComputedComponent {
  salary_component_id:   string
  name:                  string
  code:                  string
  component_type:        'earning' | 'deduction' | 'employer_contribution'
  calc_type:             string
  value:                 number
  sequence:              number
  is_basic:              boolean
  affects_pf:            boolean
  affects_nlc:           boolean
  /** Rupees / month (stored in employee_compensation_components.computed_monthly) */
  monthly_amount:        number
  /** Rupees / year  (stored in employee_compensation_components.computed_annual) */
  annual_amount:         number
  /**
   * True when this component was generated by the engine (PF entries).
   * The route layer must resolve the salary_component_id before persisting.
   */
  is_engine_generated?: boolean
}

export interface CompensationTotals {
  gross_monthly:                   number
  gross_annual:                    number
  basic_monthly:                   number
  basic_annual:                    number
  deductions_monthly:              number
  deductions_annual:               number
  employer_contributions_monthly:  number
  employer_contributions_annual:   number
  /** gross - employee deductions */
  net_monthly:                     number
  net_annual:                      number
}

export interface CompensationResult {
  components:      ComputedComponent[]
  totals:          CompensationTotals
  nlc_applied:     boolean
  pf_applied:      boolean
  /** Basic + NLC-tagged as % of Gross, post-adjustment.  null if NLC disabled. */
  nlc_wage_pct:    number | null
  /** Total annual cost actually allocated = gross + employer contributions. */
  total_cost_annual: number
  /** ctcAnnual − total_cost_annual. 0 (±₹1) when the structure reconciles to CTC. */
  residual_annual:   number
  /** True when total_cost_annual matches ctcAnnual within ₹1. */
  ctc_reconciled:    boolean
}

// ── Built-in defaults ─────────────────────────────────────────────────────────

export const DEFAULT_COMPENSATION_POLICY: Readonly<CompensationPolicy> = Object.freeze({
  nlc_enabled:      true,
  pf_enabled:       false,    // off by default; tenant opts in
  pf_employee_rate: 12.0,
  pf_employer_rate: 12.0,
  pf_cap_amount:    15_000,   // ₹15,000 / month (EPF Act ceiling)
})

// ── PF sentinel IDs ───────────────────────────────────────────────────────────
// Route layer replaces these with real salary_component.id values before
// persisting to employee_compensation_components.

export const PF_EMPLOYEE_SENTINEL = '__pf_employee__'
export const PF_EMPLOYER_SENTINEL = '__pf_employer__'
export const PF_EMPLOYEE_CODE     = 'PF_EMPLOYEE'
export const PF_EMPLOYER_CODE     = 'PF_EMPLOYER'

// ── Internal helpers ──────────────────────────────────────────────────────────

/** Round to 2 decimal places (financial rounding) */
function r2(n: number): number {
  return Math.round(n * 100) / 100
}

/** Accumulate annual amounts for a subset of computed components */
function sumAnnual(comps: ComputedComponent[]): number {
  return r2(comps.reduce((acc, c) => acc + c.annual_amount, 0))
}

// ── Main export ───────────────────────────────────────────────────────────────

export interface ComputeCompensationParams {
  ctcAnnual:  number
  components: ComponentInput[]
  employee:   EmployeeFlags
  policy:     CompensationPolicy
}

/**
 * computeCompensation
 *
 * Pure function — no side effects, no DB calls.
 * Input `value` fields are NEVER mutated; NLC/PF adjustments are reflected
 * exclusively in the returned monthly_amount / annual_amount fields.
 *
 * Throws:
 *   - 'CTC_INVALID'   if ctcAnnual ≤ 0
 *   - 'NO_COMPONENTS' if the components array is empty
 *   - 'MISSING_BASIC' if any pct_of_basic earning exists without a BASIC anchor
 *   - 'CIRCULAR_DEP'  if a pct_of_gross component depends on itself  (not possible
 *                     via current calc_type set, but guard remains for safety)
 */
export function computeCompensation({
  ctcAnnual,
  components,
  employee,
  policy,
}: ComputeCompensationParams): CompensationResult {

  // ── Guard: validate inputs ─────────────────────────────────────────────────
  if (ctcAnnual <= 0)       throw Object.assign(new Error('CTC must be positive'),            { code: 'CTC_INVALID'   })
  if (!components.length)   throw Object.assign(new Error('At least one component required'), { code: 'NO_COMPONENTS' })

  // ── Separate by component_type; sort each group by sequence ────────────────
  const earnings        = components.filter(c => c.component_type === 'earning').sort((a, b) => a.sequence - b.sequence)
  const deductions      = components.filter(c => c.component_type === 'deduction').sort((a, b) => a.sequence - b.sequence)
  const employerContrib = components.filter(c => c.component_type === 'employer_contribution').sort((a, b) => a.sequence - b.sequence)

  const basicComp     = earnings.find(c => c.is_basic)
                        ?? earnings.find(c => c.calc_type === 'fixed' || c.calc_type === 'pct_of_ctc')
  const balanceComp   = earnings.find(c => c.calc_type === 'balance')
  const hasPctOfBasic = earnings.some(c => c.calc_type === 'pct_of_basic')

  if (hasPctOfBasic && !basicComp) {
    throw Object.assign(
      new Error(
        'BASIC salary component not found. Mark one earning with is_basic=true, ' +
        'or ensure a fixed/pct_of_ctc earning precedes pct_of_basic components.',
      ),
      { code: 'MISSING_BASIC' },
    )
  }

  const pfEligible = !!(policy.pf_enabled && employee.pf_enabled && basicComp)

  // ── Pure derivation for a given Basic (annual) ─────────────────────────────
  // CTC model is ALL-INCLUSIVE: CTC = Σ earnings + Σ employer contributions.
  // The 'balance' earning (Special Allowance) absorbs the residual so the
  // structure reconciles to CTC exactly. Employee deductions live WITHIN gross
  // (they reduce net, not CTC).
  function derive(basicAnnual: number) {
    const amt = new Map<string, number>()

    // pct_of_ctc earnings (non-balance)
    for (const c of earnings) if (c.calc_type === 'pct_of_ctc') amt.set(c.salary_component_id, r2((c.value / 100) * ctcAnnual))
    // Basic anchor
    if (basicComp) amt.set(basicComp.salary_component_id, r2(basicAnnual))
    // pct_of_basic earnings
    for (const c of earnings) if (c.calc_type === 'pct_of_basic') amt.set(c.salary_component_id, r2((c.value / 100) * basicAnnual))
    // fixed (non-basic) earnings
    for (const c of earnings) if (c.calc_type === 'fixed' && !c.is_basic) amt.set(c.salary_component_id, r2(c.value * 12))
    // pct_of_gross earnings — on the running sum of non-balance earnings
    let nbGross = earnings
      .filter(c => c.calc_type !== 'balance' && c.calc_type !== 'pct_of_gross')
      .reduce((s, c) => s + (amt.get(c.salary_component_id) ?? 0), 0)
    for (const c of earnings) if (c.calc_type === 'pct_of_gross') {
      const a = r2((c.value / 100) * nbGross); amt.set(c.salary_component_id, a); nbGross = r2(nbGross + a)
    }

    // Non-balance earnings total — fixed, independent of employer contributions/balance
    const nonBalanceEarnings = r2(earnings.filter(c => c.calc_type !== 'balance')
      .reduce((s, c) => s + (amt.get(c.salary_component_id) ?? 0), 0))

    // Employer contributions that don't depend on gross (structure-defined: gratuity, etc.)
    const pctGrossEmployerComps = employerContrib.filter(c => c.calc_type === 'pct_of_gross')
    let employerFixedAnnual = 0
    for (const c of employerContrib) {
      if (c.calc_type === 'pct_of_gross') continue
      let a = 0
      switch (c.calc_type) {
        case 'fixed':        a = r2(c.value * 12);                  break
        case 'pct_of_ctc':   a = r2((c.value / 100) * ctcAnnual);   break
        case 'pct_of_basic': a = r2((c.value / 100) * basicAnnual); break
        case 'balance':      a = 0;                                 break  // not valid for employer lines
      }
      amt.set(c.salary_component_id, a)
      employerFixedAnnual = r2(employerFixedAnnual + a)
    }

    // Engine-injected PF (employer side counts toward CTC; employee side is a deduction within gross)
    let pfEmployeeAnnual = 0, pfEmployerAnnual = 0
    if (pfEligible) {
      // PF wage base is Basic plus any other earning flagged affects_pf (e.g. DA) —
      // migration 048's own doc comment: "Typical: only Basic. Some employers
      // include DA too." This previously ignored affects_pf entirely and based
      // PF on Basic alone, silently understating PF for any tenant that flags
      // a second component (DA is a standard Indian-payroll setup).
      const pfWageAnnual = r2(basicAnnual + earnings
        .filter(c => !c.is_basic && c.affects_pf && c.calc_type !== 'balance')
        .reduce((s, c) => s + (amt.get(c.salary_component_id) ?? 0), 0))
      const pfBaseMonthly = r2(pfWageAnnual / 12)
      const pfBase = employee.pf_capped ? r2(Math.min(pfBaseMonthly, policy.pf_cap_amount)) : pfBaseMonthly
      pfEmployeeAnnual = r2(r2(pfBase * (policy.pf_employee_rate / 100)) * 12)
      pfEmployerAnnual = r2(r2(pfBase * (policy.pf_employer_rate / 100)) * 12)
      employerFixedAnnual = r2(employerFixedAnnual + pfEmployerAnnual)
    }

    // Employer pct_of_gross contributions (e.g. employer-side ESI) must share the
    // SAME wage base as the employee-side pct_of_gross deductions below — the
    // FINAL gross, including the balance (Special Allowance) component. But final
    // gross depends on the balance, which depends on employerAnnual (CTC model:
    // balance absorbs CTC − employerAnnual − nonBalanceEarnings), which in turn
    // depends on these very contributions — a genuine circular dependency.
    // Resolved the same way the NLC solve resolves Basic-vs-Gross below:
    // fixed-point iteration (statutory employer rates are small percentages, so
    // this contracts and converges in a handful of passes).
    let employerAnnual = employerFixedAnnual
    let balanceAnnual   = 0
    let grossAnnual      = nonBalanceEarnings
    for (let i = 0; i < 50; i++) {
      let pctGrossSum = 0
      for (const c of pctGrossEmployerComps) pctGrossSum = r2(pctGrossSum + r2((c.value / 100) * grossAnnual))
      const nextEmployerAnnual = r2(employerFixedAnnual + pctGrossSum)
      const nextRawBalance     = r2(ctcAnnual - nextEmployerAnnual - nonBalanceEarnings)
      const nextBalanceAnnual  = balanceComp ? Math.max(0, nextRawBalance) : 0
      const nextGrossAnnual    = r2(nonBalanceEarnings + nextBalanceAnnual)
      const converged = Math.abs(nextGrossAnnual - grossAnnual) < 0.01 && Math.abs(nextEmployerAnnual - employerAnnual) < 0.01
      employerAnnual = nextEmployerAnnual
      balanceAnnual  = nextBalanceAnnual
      grossAnnual    = nextGrossAnnual
      if (converged) break
    }
    for (const c of pctGrossEmployerComps) amt.set(c.salary_component_id, r2((c.value / 100) * grossAnnual))

    const rawBalance = r2(ctcAnnual - employerAnnual - nonBalanceEarnings)
    if (balanceComp) amt.set(balanceComp.salary_component_id, balanceAnnual)
    const nlcWage = r2((basicComp ? basicAnnual : 0) + earnings
      .filter(c => !c.is_basic && c.affects_nlc && c.calc_type !== 'balance')
      .reduce((s, c) => s + (amt.get(c.salary_component_id) ?? 0), 0))

    return { amt, basicAnnual, employerAnnual, nonBalanceEarnings, balanceAnnual, rawBalance, grossAnnual, nlcWage, pfEmployeeAnnual, pfEmployerAnnual }
  }

  // ── Initial Basic from the structure ───────────────────────────────────────
  let basic0 = 0
  if (basicComp) {
    if (basicComp.calc_type === 'fixed')           basic0 = r2(basicComp.value * 12)
    else if (basicComp.calc_type === 'pct_of_ctc') basic0 = r2((basicComp.value / 100) * ctcAnnual)
  }
  if (basicComp && basic0 <= 0 && balanceComp) {
    // Basic not directly priced (e.g. only % of basic siblings) — seed at 40% of CTC.
    basic0 = r2(0.4 * ctcAnnual)
  }

  let d = derive(basic0)

  // ── NLC enforcement: Basic + NLC-tagged ≥ 50% of Gross ─────────────────────
  // Funded by shifting money from the balance (Special Allowance) into Basic.
  // Increasing Basic raises the NLC wage and (via larger employer contributions)
  // lowers Gross, so the ratio rises monotonically — solve by bisection.
  let nlcApplied = false
  let nlcWagePct: number | null = policy.nlc_enabled ? (d.grossAnnual > 0 ? r2((d.nlcWage / d.grossAnnual) * 100) : 0) : null

  if (policy.nlc_enabled && basicComp && balanceComp && d.grossAnnual > 0 && d.nlcWage < r2(0.5 * d.grossAnnual) && d.rawBalance > 0) {
    let lo = basic0
    let hi = r2(basic0 + d.rawBalance)   // upper bound: pull the entire balance into Basic
    let best = d
    for (let i = 0; i < 48; i++) {
      const mid = r2((lo + hi) / 2)
      const dm  = derive(mid)
      const pct = dm.grossAnnual > 0 ? (dm.nlcWage / dm.grossAnnual) * 100 : 0
      if (dm.rawBalance < 0) { hi = mid; continue }    // overshoot — Basic too high, balance went negative
      if (pct >= 50) { hi = mid; best = dm } else { lo = mid }
      if (hi - lo < 1) break
    }
    if (best.rawBalance >= -1 && best.grossAnnual > 0 && (best.nlcWage / best.grossAnnual) * 100 >= 49.5) {
      d = best
      nlcApplied = true
    }
    nlcWagePct = d.grossAnnual > 0 ? r2((d.nlcWage / d.grossAnnual) * 100) : 0
  }

  const basicAnnual = d.basicAnnual

  // ── Employee deductions (within gross; pct_of_gross uses final gross) ──────
  for (const c of deductions) {
    let a = 0
    switch (c.calc_type) {
      case 'fixed':        a = r2(c.value * 12);                  break
      case 'pct_of_ctc':   a = r2((c.value / 100) * ctcAnnual);   break
      case 'pct_of_basic': a = r2((c.value / 100) * basicAnnual); break
      case 'pct_of_gross': a = r2((c.value / 100) * d.grossAnnual); break
      case 'balance':      a = 0;                                 break
    }
    d.amt.set(c.salary_component_id, a)
  }

  // ── Engine-injected PF components ──────────────────────────────────────────
  const pfComponents: ComputedComponent[] = []
  let pfApplied = false
  if (pfEligible) {
    pfApplied = true
    const empPfMonthly = r2(d.pfEmployeeAnnual / 12)
    const erPfMonthly  = r2(d.pfEmployerAnnual / 12)
    pfComponents.push({
      salary_component_id: PF_EMPLOYEE_SENTINEL, name: 'PF Employee Contribution', code: PF_EMPLOYEE_CODE,
      component_type: 'deduction', calc_type: 'pct_of_basic', value: policy.pf_employee_rate, sequence: 9000,
      is_basic: false, affects_pf: false, affects_nlc: false,
      monthly_amount: empPfMonthly, annual_amount: d.pfEmployeeAnnual, is_engine_generated: true,
    })
    pfComponents.push({
      salary_component_id: PF_EMPLOYER_SENTINEL, name: 'PF Employer Contribution', code: PF_EMPLOYER_CODE,
      component_type: 'employer_contribution', calc_type: 'pct_of_basic', value: policy.pf_employer_rate, sequence: 9001,
      is_basic: false, affects_pf: false, affects_nlc: false,
      monthly_amount: erPfMonthly, annual_amount: d.pfEmployerAnnual, is_engine_generated: true,
    })
  }

  // ── Build ComputedComponent list ───────────────────────────────────────────
  const inputComputed: ComputedComponent[] = [...earnings, ...deductions, ...employerContrib].map(c => {
    const annual = d.amt.get(c.salary_component_id) ?? 0
    return {
      salary_component_id: c.salary_component_id, name: c.name, code: c.code,
      component_type: c.component_type, calc_type: c.calc_type, value: c.value, sequence: c.sequence,
      is_basic: c.is_basic, affects_pf: c.affects_pf, affects_nlc: c.affects_nlc,
      monthly_amount: r2(annual / 12), annual_amount: annual,
    }
  })

  const allComponents = [...inputComputed, ...pfComponents]

  // ── Totals ─────────────────────────────────────────────────────────────────
  const grossAnnualFinal  = sumAnnual(allComponents.filter(c => c.component_type === 'earning'))
  const deductAnnual      = sumAnnual(allComponents.filter(c => c.component_type === 'deduction'))
  const employerConAnnual = sumAnnual(allComponents.filter(c => c.component_type === 'employer_contribution'))

  const totals: CompensationTotals = {
    gross_annual:                   grossAnnualFinal,
    gross_monthly:                  r2(grossAnnualFinal / 12),
    basic_annual:                   r2(basicAnnual),
    basic_monthly:                  r2(basicAnnual / 12),
    deductions_annual:              deductAnnual,
    deductions_monthly:             r2(deductAnnual / 12),
    employer_contributions_annual:  employerConAnnual,
    employer_contributions_monthly: r2(employerConAnnual / 12),
    net_annual:                     r2(grossAnnualFinal - deductAnnual),
    net_monthly:                    r2((grossAnnualFinal - deductAnnual) / 12),
  }

  // CTC reconciliation = gross + employer contributions (all-inclusive model).
  const totalCostAnnual = r2(grossAnnualFinal + employerConAnnual)
  const residualAnnual  = r2(ctcAnnual - totalCostAnnual)
  const ctcReconciled   = Math.abs(residualAnnual) <= 1

  return {
    components:        allComponents,
    totals,
    nlc_applied:       nlcApplied,
    pf_applied:        pfApplied,
    nlc_wage_pct:      policy.nlc_enabled ? nlcWagePct : null,
    total_cost_annual: totalCostAnnual,
    residual_annual:   residualAnnual,
    ctc_reconciled:    ctcReconciled,
  }
}
