-- =============================================================
-- 047_attendance_anomalies.sql
--
-- Attendance anomaly tracking table.
--
-- The AttendanceEngine writes anomaly rows automatically when it
-- detects abnormal conditions during attendance computation.
-- Employees and HR can view, filter, and resolve anomalies via the
-- Anomalies UI and API.
--
-- Anomaly types:
--   missing_out      — employee has an IN punch with no matching OUT
--   no_punch         — employee has zero punches on a working day
--   late             — employee arrived after grace + policy late threshold
--   excessive_hours  — employee logged more hours than the excessive_hours
--                      threshold defined in their attendance policy
--
-- Severity:
--   low    — informational, auto-resolved on recompute when condition gone
--   medium — notable deviation, surfaced in dashboard
--   high   — action required (e.g. no punch for 3+ days)
--
-- Deduplication:
--   A UNIQUE constraint on (tenant_id, employee_id, date, type) ensures the
--   engine can upsert without creating duplicate rows for the same anomaly.
--   The engine uses an UPSERT approach: reinsert/update if the anomaly still
--   applies, or delete if it no longer applies.
--
-- Resolution:
--   resolved        — toggled true by HR when the anomaly is acknowledged.
--   resolved_by     — profiles.id of the resolver.
--   resolved_at     — timestamp of resolution.
--   Resolved anomalies are NOT deleted; they stay as a historical record.
-- =============================================================

CREATE TABLE IF NOT EXISTS attendance_anomalies (
  id           UUID  PRIMARY KEY DEFAULT gen_random_uuid(),

  tenant_id    UUID  NOT NULL REFERENCES tenants(id)   ON DELETE CASCADE,
  employee_id  UUID  NOT NULL REFERENCES employees(id) ON DELETE CASCADE,

  -- Tenant-local calendar date (YYYY-MM-DD) of the anomalous day
  date         DATE  NOT NULL,

  -- Category of anomaly
  type         TEXT  NOT NULL
    CONSTRAINT att_anomaly_type_check
      CHECK (type IN ('missing_out', 'no_punch', 'late', 'excessive_hours')),

  -- Human-readable description generated by the engine
  message      TEXT  NOT NULL,

  -- How urgent / visible this anomaly is
  severity     TEXT  NOT NULL DEFAULT 'low'
    CONSTRAINT att_anomaly_severity_check
      CHECK (severity IN ('low', 'medium', 'high')),

  -- Has an HR user marked this as acknowledged / resolved?
  resolved     BOOLEAN      NOT NULL DEFAULT false,
  resolved_by  UUID         NULL REFERENCES profiles(id) ON DELETE SET NULL,
  resolved_at  TIMESTAMPTZ  NULL,

  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

  -- One active anomaly row per (employee, date, type) — prevents duplicates
  -- when the engine recomputes the same date multiple times.
  UNIQUE (tenant_id, employee_id, date, type)
);

-- Query patterns:
--   • List unresolved anomalies for a tenant (HR dashboard)
--   • List anomalies for one employee (employee self-view)
--   • Filter by date range + type
CREATE INDEX IF NOT EXISTS idx_att_anomaly_employee
  ON attendance_anomalies (tenant_id, employee_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_att_anomaly_unresolved
  ON attendance_anomalies (tenant_id, resolved, created_at DESC)
  WHERE resolved = false;

CREATE INDEX IF NOT EXISTS idx_att_anomaly_type
  ON attendance_anomalies (tenant_id, type, date DESC);

-- ── Row-level security ────────────────────────────────────────

ALTER TABLE attendance_anomalies ENABLE ROW LEVEL SECURITY;

-- Employees see only their own anomalies
CREATE POLICY "aa_employee_read" ON attendance_anomalies
  FOR SELECT
  USING (
    tenant_id = get_user_tenant_id()
    AND (
      get_user_role() IN ('super_admin', 'hr_admin')
      OR employee_id = (
        SELECT employee_id FROM profiles
        WHERE id = auth.uid()
        LIMIT 1
      )
    )
  );

-- HR can insert/update/delete
CREATE POLICY "aa_hr_write" ON attendance_anomalies
  FOR ALL
  USING (get_user_role() IN ('super_admin', 'hr_admin'));

-- System (service role) bypasses RLS — needed for engine writes

-- ── Comments ──────────────────────────────────────────────────

COMMENT ON TABLE  attendance_anomalies IS
  'Anomalous attendance conditions detected by the AttendanceEngine. '
  'HR can filter, view details, and mark anomalies as resolved.';

COMMENT ON COLUMN attendance_anomalies.type IS
  'Anomaly category: missing_out | no_punch | late | excessive_hours';

COMMENT ON COLUMN attendance_anomalies.severity IS
  'Urgency level: low (informational) | medium (notable) | high (action required)';

COMMENT ON COLUMN attendance_anomalies.resolved IS
  'True once an HR admin has acknowledged and resolved the anomaly. '
  'Resolved rows are retained for audit history.';
