-- ============================================================
-- 079_payroll_forecasts.sql
--
-- Stores generated payroll forecasts for upcoming months.
-- Forecasts are generated by the forecast engine using:
--   - Active compensation records (expected gross)
--   - Historical OT patterns (3-month rolling avg)
--   - Pending compensation revisions (effective date aware)
--   - Headcount projection (active employees)
--   - Leave-heavy period multiplier
--
-- One forecast per tenant per target_month (UNIQUE).
-- Regenerating overwrites the existing row (upsert).
-- ============================================================

CREATE TABLE IF NOT EXISTS payroll_forecasts (
  id                      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id               UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  target_month            TEXT          NOT NULL,   -- YYYY-MM format
  generated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
  generated_by            TEXT          NOT NULL DEFAULT 'system',  -- 'system' | profile UUID

  -- Headline numbers
  forecast_headcount      INT           NOT NULL DEFAULT 0,
  forecast_total_gross    NUMERIC(14,2) NOT NULL DEFAULT 0,
  forecast_total_net      NUMERIC(14,2) NOT NULL DEFAULT 0,
  forecast_total_ot_cost  NUMERIC(14,2) NOT NULL DEFAULT 0,

  -- Baseline comparison
  base_month              TEXT          NULL,           -- YYYY-MM of reference month
  base_total_gross        NUMERIC(14,2) NULL,
  variance_pct            NUMERIC(6,2)  NULL,           -- vs base month

  -- Forecast confidence (0–100)
  confidence_pct          INT           NOT NULL DEFAULT 80
    CHECK (confidence_pct BETWEEN 0 AND 100),

  -- Breakdown details (JSONB for flexibility across tenants)
  by_department   JSONB NULL,
  -- [{ department_id, department_name, headcount, forecast_gross, forecast_ot }]

  risk_factors    JSONB NULL,
  -- [{ type, description, impact_amount, severity }]
  -- types: ot_trend, pending_revision, leave_heavy_period, staffing_shortage

  assumptions     JSONB NULL,
  -- [{ key, label, value }]
  -- e.g. ot_multiplier, revision_count, base_headcount

  UNIQUE (tenant_id, target_month)
);

CREATE INDEX IF NOT EXISTS idx_payroll_forecasts_tenant_month
  ON payroll_forecasts (tenant_id, target_month DESC);

ALTER TABLE payroll_forecasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "forecast_tenant_read" ON payroll_forecasts FOR SELECT
  USING (tenant_id = get_user_tenant_id());

CREATE POLICY "forecast_hr_write" ON payroll_forecasts FOR ALL
  USING (get_user_role() IN ('super_admin', 'hr_admin'));
