-- Migration 232: Statutory Filing Artifacts
--
-- Tracks every compliance file generated by the Filing Pack feature.
-- Immutable audit record: captures what was generated, by whom, and its
-- lifecycle status as it moves through Generated → Submitted → Acknowledged.

CREATE TABLE IF NOT EXISTS statutory_filing_artifacts (
  id              UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id       UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  -- What was generated
  artifact_type   TEXT          NOT NULL
                    CHECK (artifact_type IN ('ecr_2_0', '24q', 'challan_epf', 'challan_esi', 'challan_ptax', 'challan_tds', 'challan_all')),
  -- Period identifiers (one or more will be set depending on artifact_type)
  period_month    TEXT,                  -- YYYY-MM (monthly artifacts)
  period_quarter  SMALLINT               CHECK (period_quarter BETWEEN 1 AND 4),
  period_fy       TEXT,                  -- YYYY-YY (financial year, e.g. "2024-25")

  -- File metadata
  file_name       TEXT          NOT NULL,
  row_count       INTEGER,

  -- Lifecycle
  status          TEXT          NOT NULL DEFAULT 'generated'
                    CHECK (status IN ('generated', 'submitted', 'acknowledged')),
  generated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  generated_by    UUID          REFERENCES profiles(id) ON DELETE SET NULL,
  submitted_at    TIMESTAMPTZ,
  acknowledged_at TIMESTAMPTZ,
  notes           TEXT,

  created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_filing_artifacts_tenant_period
  ON statutory_filing_artifacts (tenant_id, period_month, period_fy, artifact_type);

CREATE INDEX IF NOT EXISTS idx_filing_artifacts_tenant_status
  ON statutory_filing_artifacts (tenant_id, status, generated_at DESC);

-- RLS
ALTER TABLE statutory_filing_artifacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation_filing_artifacts"
  ON statutory_filing_artifacts
  USING (tenant_id = (SELECT tenant_id FROM profiles WHERE id = auth.uid()));

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_filing_artifacts_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_filing_artifacts_updated_at ON statutory_filing_artifacts;
CREATE TRIGGER trg_filing_artifacts_updated_at
  BEFORE UPDATE ON statutory_filing_artifacts
  FOR EACH ROW EXECUTE FUNCTION update_filing_artifacts_updated_at();
